Update PHP.yml

diff --git a/.github/workflows/PHP.yml b/.github/workflows/PHP.yml
--- a/.github/workflows/PHP.yml
+++ b/.github/workflows/PHP.yml
@@ -35,8 +35,9 @@ jobs:
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
       - name: Rebase production on top of main
-        run: | 
+        run: |
          git checkout production
-         git rebase main
+         git rebase main || (echo "Conflict detected during rebase. Please handle manually." && git rebase --abort && exit 1)
          git push origin production --force-with-lease
+
 
